### PR TITLE
Allow to connect from remote machine

### PR DESCRIPTION
**Pull request by richardklafter**
Allows connection from remote machine by replacing the hostname in urls with [res.connection.localAddress](https://nodejs.org/api/net.html#net_socket_localaddress). Supports IPv6.

### CODE REVIEW

**Comment by sidorares** [comment]
lgtm! @lostintangent can I have extra pair of eyes on this?

**Comment by sidorares** [comment]
@richardklafter I slightly edited your comment on #2 so that gh cross-links correctly

**Comment by richardklafter** [comment]
ping?

**Comment by lostintangent** [comment]
LGTM as well!

**Comment by sidorares** [comment]
oh sorry @richardklafter forgot about this

looks good to me, will merge after @lostintangent review

**Pull request merged**
